name: ci
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
    branches:
      - main
      - 'feature/**'

jobs:
  build:
    if: ! github.event.pull_request.draft
    name: ci build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn lint
      - name: vitest test
        run: yarn test
      - name: vitest coverage
        run: yarn coverage
      - name: next build
        run: yarn build
